[package]
name = "BedrockStationRust"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.12.1", features = ["renderer-software"] }
regex = "1.12.2"
process_alive = "0.1.1"
interprocess = "2.2.3"

[build-dependencies]
slint-build = "1.12.1"
winresource = "0.1.23"
